APPLY_FIXES: none
DEFAULT_BRANCH: main

ENABLE:
  - PYTHON_BLACK
  - PYTHON_ISORT
  - PYTHON_FLAKE8
  - PYTHON_PYLINT
  - PYTHON_MYPY
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - DOCKERFILE_HADOLINT
  - ACTION_ACTIONLINT

DISABLE:
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - YAML_PRETTIER
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
  - PYTHON_BANDIT
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_GRYPE
  - REPOSITORY_SYFT
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT

